name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.HOSTING_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub cache repair
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email mohil.0510@gmail.com
          git config --global user.name mohilthummar
          git status
          git remote add origin https://${{secrets.HOSTING_SECRET}}@github.com/mohilthummar/task_app.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Web Updated"
          git push origin gh-pages -f
