name: Flutter Web
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{ secrets.HOSTING_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # In lines 24 and 25 type your email ID and username respectively
          git config --global user.email mohil.0510@gmail.com
          git config --global user.name mohilthummar
          git status
          # in line 30 after @ add your repo link  
          git remote add origin https://${{ secrets.HOSTING_SECRET }}@https://github.com/mohilthummar/task_app.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Web Updated"
          git push origin gh-pages -f
